/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatSessionKeyRouteImport } from './routes/chat/$sessionKey'
import { Route as ApiWorkspacesRouteImport } from './routes/api/workspaces'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSessionBundleRouteImport } from './routes/api/session-bundle'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiRunEventsRouteImport } from './routes/api/run-events'
import { Route as ApiRepoContextRouteImport } from './routes/api/repo-context'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiPathsRouteImport } from './routes/api/paths'
import { Route as ApiMcpHealthRouteImport } from './routes/api/mcp-health'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiGitReviewRouteImport } from './routes/api/git-review'
import { Route as ApiContextPreviewRouteImport } from './routes/api/context-preview'
import { Route as ApiArtifactsRouteImport } from './routes/api/artifacts'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionKeyRoute = ChatSessionKeyRouteImport.update({
  id: '/chat/$sessionKey',
  path: '/chat/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesRoute = ApiWorkspacesRouteImport.update({
  id: '/api/workspaces',
  path: '/api/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionBundleRoute = ApiSessionBundleRouteImport.update({
  id: '/api/session-bundle',
  path: '/api/session-bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunEventsRoute = ApiRunEventsRouteImport.update({
  id: '/api/run-events',
  path: '/api/run-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepoContextRoute = ApiRepoContextRouteImport.update({
  id: '/api/repo-context',
  path: '/api/repo-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPathsRoute = ApiPathsRouteImport.update({
  id: '/api/paths',
  path: '/api/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpHealthRoute = ApiMcpHealthRouteImport.update({
  id: '/api/mcp-health',
  path: '/api/mcp-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitReviewRoute = ApiGitReviewRouteImport.update({
  id: '/api/git-review',
  path: '/api/git-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContextPreviewRoute = ApiContextPreviewRouteImport.update({
  id: '/api/context-preview',
  path: '/api/context-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsRoute = ApiArtifactsRouteImport.update({
  id: '/api/artifacts',
  path: '/api/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/new': typeof NewRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/context-preview': typeof ApiContextPreviewRoute
  '/api/git-review': typeof ApiGitReviewRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/mcp-health': typeof ApiMcpHealthRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/repo-context': typeof ApiRepoContextRoute
  '/api/run-events': typeof ApiRunEventsRoute
  '/api/send': typeof ApiSendRoute
  '/api/session-bundle': typeof ApiSessionBundleRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tasks': typeof ApiTasksRoute
  '/api/workspaces': typeof ApiWorkspacesRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/new': typeof NewRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/context-preview': typeof ApiContextPreviewRoute
  '/api/git-review': typeof ApiGitReviewRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/mcp-health': typeof ApiMcpHealthRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/repo-context': typeof ApiRepoContextRoute
  '/api/run-events': typeof ApiRunEventsRoute
  '/api/send': typeof ApiSendRoute
  '/api/session-bundle': typeof ApiSessionBundleRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tasks': typeof ApiTasksRoute
  '/api/workspaces': typeof ApiWorkspacesRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/new': typeof NewRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/context-preview': typeof ApiContextPreviewRoute
  '/api/git-review': typeof ApiGitReviewRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/mcp-health': typeof ApiMcpHealthRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/repo-context': typeof ApiRepoContextRoute
  '/api/run-events': typeof ApiRunEventsRoute
  '/api/send': typeof ApiSendRoute
  '/api/session-bundle': typeof ApiSessionBundleRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tasks': typeof ApiTasksRoute
  '/api/workspaces': typeof ApiWorkspacesRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/new'
    | '/api/artifacts'
    | '/api/context-preview'
    | '/api/git-review'
    | '/api/history'
    | '/api/mcp-health'
    | '/api/paths'
    | '/api/ping'
    | '/api/repo-context'
    | '/api/run-events'
    | '/api/send'
    | '/api/session-bundle'
    | '/api/sessions'
    | '/api/stream'
    | '/api/tasks'
    | '/api/workspaces'
    | '/chat/$sessionKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/new'
    | '/api/artifacts'
    | '/api/context-preview'
    | '/api/git-review'
    | '/api/history'
    | '/api/mcp-health'
    | '/api/paths'
    | '/api/ping'
    | '/api/repo-context'
    | '/api/run-events'
    | '/api/send'
    | '/api/session-bundle'
    | '/api/sessions'
    | '/api/stream'
    | '/api/tasks'
    | '/api/workspaces'
    | '/chat/$sessionKey'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/new'
    | '/api/artifacts'
    | '/api/context-preview'
    | '/api/git-review'
    | '/api/history'
    | '/api/mcp-health'
    | '/api/paths'
    | '/api/ping'
    | '/api/repo-context'
    | '/api/run-events'
    | '/api/send'
    | '/api/session-bundle'
    | '/api/sessions'
    | '/api/stream'
    | '/api/tasks'
    | '/api/workspaces'
    | '/chat/$sessionKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  NewRoute: typeof NewRoute
  ApiArtifactsRoute: typeof ApiArtifactsRoute
  ApiContextPreviewRoute: typeof ApiContextPreviewRoute
  ApiGitReviewRoute: typeof ApiGitReviewRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiMcpHealthRoute: typeof ApiMcpHealthRoute
  ApiPathsRoute: typeof ApiPathsRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiRepoContextRoute: typeof ApiRepoContextRoute
  ApiRunEventsRoute: typeof ApiRunEventsRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSessionBundleRoute: typeof ApiSessionBundleRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiTasksRoute: typeof ApiTasksRoute
  ApiWorkspacesRoute: typeof ApiWorkspacesRoute
  ChatSessionKeyRoute: typeof ChatSessionKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionKey': {
      id: '/chat/$sessionKey'
      path: '/chat/$sessionKey'
      fullPath: '/chat/$sessionKey'
      preLoaderRoute: typeof ChatSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces': {
      id: '/api/workspaces'
      path: '/api/workspaces'
      fullPath: '/api/workspaces'
      preLoaderRoute: typeof ApiWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-bundle': {
      id: '/api/session-bundle'
      path: '/api/session-bundle'
      fullPath: '/api/session-bundle'
      preLoaderRoute: typeof ApiSessionBundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run-events': {
      id: '/api/run-events'
      path: '/api/run-events'
      fullPath: '/api/run-events'
      preLoaderRoute: typeof ApiRunEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repo-context': {
      id: '/api/repo-context'
      path: '/api/repo-context'
      fullPath: '/api/repo-context'
      preLoaderRoute: typeof ApiRepoContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paths': {
      id: '/api/paths'
      path: '/api/paths'
      fullPath: '/api/paths'
      preLoaderRoute: typeof ApiPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-health': {
      id: '/api/mcp-health'
      path: '/api/mcp-health'
      fullPath: '/api/mcp-health'
      preLoaderRoute: typeof ApiMcpHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/git-review': {
      id: '/api/git-review'
      path: '/api/git-review'
      fullPath: '/api/git-review'
      preLoaderRoute: typeof ApiGitReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/context-preview': {
      id: '/api/context-preview'
      path: '/api/context-preview'
      fullPath: '/api/context-preview'
      preLoaderRoute: typeof ApiContextPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts': {
      id: '/api/artifacts'
      path: '/api/artifacts'
      fullPath: '/api/artifacts'
      preLoaderRoute: typeof ApiArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  NewRoute: NewRoute,
  ApiArtifactsRoute: ApiArtifactsRoute,
  ApiContextPreviewRoute: ApiContextPreviewRoute,
  ApiGitReviewRoute: ApiGitReviewRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiMcpHealthRoute: ApiMcpHealthRoute,
  ApiPathsRoute: ApiPathsRoute,
  ApiPingRoute: ApiPingRoute,
  ApiRepoContextRoute: ApiRepoContextRoute,
  ApiRunEventsRoute: ApiRunEventsRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSessionBundleRoute: ApiSessionBundleRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiTasksRoute: ApiTasksRoute,
  ApiWorkspacesRoute: ApiWorkspacesRoute,
  ChatSessionKeyRoute: ChatSessionKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
